config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "lists#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:index, :create, :destroy, :edit, :update]
    resources :reviews, only: [:index, :new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :reviews
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :restrict_with_error
  validates :title, uniqueness: true
  validates :overview, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:create, :destroy, :edit, :update]
  before_action :set_bookmark, only: [:edit, :destroy, :edit, :update]

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
	  @bookmark.save
    redirect_to list_path(params[:list_id])
  end

  def edit
  end


  def update
    @bookmark.update(bookmark_params)
    redirect_to list_path(@list)
  end

  def destroy
	  @bookmark.destroy
    redirect_to list_path(@list),
    status: :see_other,
    notice: "Bookmark supprimé."
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(list_id: @list.id).order(created_at: :desc)
    @reviews = Review.where(list_id: @list.id)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

private

  def list_params
  	params.require(:list).permit(:name)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: [:create, :new, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    @review.save
    redirect_to list_path(params[:list_id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@list),
    status: :see_other,
    notice: "Review supprimé."
  end

  private

  def review_params
    params.require(:review).permit(:comment, :stars, :list_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/edit.html.erb
<div class="container w-75">
  <h1>Edit Bookmark ?</h1>

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, as: :radio_buttons %>
    <%= f.button :submit ,class:"btn btn-primary"%>
  <% end %>

</div>
<hr>
<%= link_to "cancel", lists_path , class:"btn btn-primary" %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <%= link_to "Movie Slayer !", lists_path, class:"navbar-brand mx-3" %>
      <form class="form-inline">
        <%= link_to "Add List", new_list_path, class:"btn btn-outline-danger m-2 my-sm-0" %>
      </form>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container card-holder w-50">
  <% @lists.each do |list| %>
    <div class="card m-2">
      <%= list.name %>
      <%= link_to "See Details", list_path(list) %>

    </div>
  <% end %>
</div>
<hr>

app/views/lists/new.html.erb
<h1>Add a list</h1>

<%= simple_form_for [@list] do |f| %>
	<%= f.input :name %>
	<%= f.submit "Create List", class: "btn btn-primary m-2" %>
<% end %>

<%= link_to "back", lists_path, class:"btn btn-secondary m-2" %>

app/views/lists/show.html.erb
<div class='main-container'>
<h1><%= @list.name %></h1>
<hr>
  <div class="container d-flex">
    <div class="row w-100">
      <div class="card-product-holder w-75 gap-2">
        <% @bookmarks.each do |bookmark| %>
          <div class="card-product">
            <img src="<%= bookmark.movie.poster_url %>" alt="film">
            <div class="card-body">
              <div class="card-body-text">
                <h2><%= bookmark.movie.title %></h5>
                <p><i>"<%= bookmark.comment %>"</i></p>
              </div>
              <div class="card-body-buttons">
                <i><%= link_to "Edit", edit_list_bookmark_path(@list, bookmark), class:"flash flash-warning"  %> </i>
                <i><%= link_to "Delete", list_bookmark_path(@list, bookmark), class:"flash flash-danger", data: { turbo_method: :delete }  %></i>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="bookmark-container w-25">
        <h4>Add New Bookmark</h4>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, as: :text, input_html: { rows: 4 } %>
          <%= f.association :movie %>
          <%= f.button :submit ,class:"btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>

  <hr>

  <h2>Reviews</h2>
  <div class="review-block">
    <div class="row w-100">
      <%= link_to "Add Review", new_list_review_path(@list), class:"flash flash-grey"%>
      <div class="reviews-list w-75">
        <ul>
          <% @reviews.each do |review| %>
          <li class="review">
            <%= review.comment %>
            <%= link_to list_review_path(@list, review), class:"fa-solid fa-circle-xmark", data: { turbo_method: :delete }  do%>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

  <%= link_to "back", lists_path, class:"btn btn-secondary m-2" %>

app/views/reviews/new.html.erb
<h1>Add Review</h1>

  <%= simple_form_for [@list, @review] do |f| %>
    <%= f.input :comment %>
    <%= f.input :stars %>
    <%= f.button :submit ,class:"btn btn-primary"%>
  <% end %>